import re
from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse
from fastapi.encoders import jsonable_encoder
from typing import Optional

from lib.itch import Itch
from api.models.itch_schema import ItchSchema

AUTHOR = "Sandy Sayang Gawr Gura"

ROUTER = APIRouter()

responses = {
	404: {
		"description": "Not found!",
		"content": {
			"application/json": {
				"example": {"author": AUTHOR, "status": 404, "message": "Not found!"}
			}
		},
	},
	406: {
		"description": "Invalid query!",
		"content": {
			"application/json": {
				"example": {
					"author": AUTHOR,
					"status": 406,
					"message": "Invalid query!",
				}
			}
		},
	},
	422: {
		"description": "Unprocessable",
		"content": {
			"application/json": {
				"example": {
					"author": AUTHOR,
					"status": 422,
					"message": "Unprocessable request!",
				}
			}
		},
	},
}


@ROUTER.get(
	"/itch",
	response_model=ItchSchema,
	responses={
		**responses,
		200: {
			"description": "Successfully response",
			"content": {
				"application/json": {
					"example": {
						"author": "Sandy Sayang Gawr Gura",
						"status": 200,
						"results": [
							{
								"id": "1300407",
								"title": "hololive å¤§æ­¦éæ ! / hololive fight festival !",
								"thumbnail": "https://img.itch.zone/aW1nLzc2MjIxNTguZ2lm/315x250%23cm/3xcz%2BL.gif",
								"url": "https://0982398818zzz.itch.io/hololive-fight-festival",
								"author": "https://0982398818zzz.itch.io",
								"genre": "Fighting",
								"caption": "holo theme smash game(wip",
							},
							{
								"id": "1023703",
								"title": "Into the Holoverse (Hololive fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzY0MjU0NjUucG5n/315x250%23c/X74Teb.png",
								"url": "https://justwastingtime.itch.io/into-the-holoverse",
								"author": "https://justwastingtime.itch.io",
								"genre": "Strategy",
								"caption": "A turn-based tactical hololive battler. Also gacha.",
							},
							{
								"id": "1204885",
								"title": "Avoid hololive MEME",
								"thumbnail": "https://img.itch.zone/aW1nLzg0ODYyODcucG5n/315x250%23c/%2Bn3O5r.png",
								"url": "https://kudeok.itch.io/avoid-hololive-meme",
								"author": "https://kudeok.itch.io",
								"genre": "Action",
								"caption": "Avoid hololive MEMbErs and MEMEs",
							},
							{
								"id": "1225699",
								"title": "Hololive ID Rumble",
								"thumbnail": "https://img.itch.zone/aW1nLzcxNDcyNjAucG5n/315x250%23c/iBeKsT.png",
								"url": "https://jackrockstar.itch.io/hololive-id-rumble",
								"author": "https://jackrockstar.itch.io",
								"genre": "Action",
								"caption": "The Hololive Indonesia branch battles people for silly reasons",
							},
							{
								"id": "1526013",
								"title": "[Hololive] Holodefense",
								"thumbnail": "https://img.itch.zone/aW1nLzkyOTA2NzgucG5n/315x250%23c/66Zwnd.png",
								"url": "https://jimlad42.itch.io/holodefense",
								"author": "https://jimlad42.itch.io",
								"genre": "Strategy",
								"caption": "A Hololive Tower Defense game.",
							},
							{
								"id": "1568908",
								"title": "Heaven2Hell Peko (Hololive Fan Game)",
								"thumbnail": "https://img.itch.zone/aW1nLzkxNjEwMDIucG5n/315x250%23c/D1nsfb.png",
								"url": "https://nycu.itch.io/heaven2hell-peko",
								"author": "https://nycu.itch.io",
								"genre": "Platformer",
								"caption": "A hololive fan game project! UwU",
							},
							{
								"id": "1593598",
								"title": "SUPER PEKO 35 (Hololive Fan Game)",
								"thumbnail": "https://img.itch.zone/aW1nLzk0MjQ3NjYucG5n/315x250%23c/043I9F.png",
								"url": "https://nycu.itch.io/super-peko-35",
								"author": "https://nycu.itch.io",
								"genre": "Platformer",
								"caption": "A 2D pixel shooter hololive fan game!",
							},
							{
								"id": "1612402",
								"title": "Holoclick (Hololive Popcat)",
								"thumbnail": "https://img.itch.zone/aW1nLzk0MzkyMzEucG5n/315x250%23c/KnJDuo.png",
								"url": "https://ollieve.itch.io/holoclick",
								"author": "https://ollieve.itch.io",
								"genre": "Simulation",
								"caption": "This is Hololive Popcat. Cheer on your favorite member with a touch.",
							},
							{
								"id": "1490585",
								"title": "The Holy Radiant Maze - Hololive ID Fan Game",
								"thumbnail": "https://img.itch.zone/aW1nLzg2OTAxOTcucG5n/315x250%23c/ZXtrR9.png",
								"url": "https://nanase.itch.io/the-holy-radiant-maze",
								"author": "https://nanase.itch.io",
								"genre": "Adventure",
								"caption": "A fan-made RPG featuring the talents of Hololive Indonesia",
							},
							{
								"id": "1673716",
								"title": "Starsnake: Hololive & Holostars Fan Game",
								"thumbnail": "https://img.itch.zone/aW1nLzk4NjI1NjkucG5n/315x250%23c/3mZ4oo.png",
								"url": "https://edgemint.itch.io/starsnake",
								"author": "https://edgemint.itch.io",
								"genre": "Rhythm",
								"caption": "Timeless classic, revisited in a Hololive theme",
							},
							{
								"id": "1571136",
								"title": "Delivering Hope (hololive fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzkzODg2NzEucG5n/315x250%23c/2vACGt.png",
								"url": "https://david-wu-softdev.itch.io/delivering-hope-hololive-fangame",
								"author": "https://david-wu-softdev.itch.io",
								"genre": "N/A",
								"caption": "How far can Hope go?",
							},
							{
								"id": "1055241",
								"title": "Five Nights at Hololive",
								"thumbnail": "https://img.itch.zone/aW1nLzYwMzc3NjkucG5n/315x250%23c/ekU9%2FZ.png",
								"url": "https://yukari-moscow.itch.io/five-nights-at-hololive",
								"author": "https://yukari-moscow.itch.io",
								"genre": "Survival",
								"caption": "N/A",
							},
							{
								"id": "671993",
								"title": "DOOG (Hololive fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzM4MjQ2NDYucG5n/315x250%23c/m0FZwQ.png",
								"url": "https://david-wu-softdev.itch.io/doog-hololive-fangame",
								"author": "https://david-wu-softdev.itch.io",
								"genre": "Shooter",
								"caption": "FPS game inspired by Inugami Korone VTuber",
							},
							{
								"id": "1437875",
								"title": "[Hololive] Mumei no Toshi",
								"thumbnail": "https://img.itch.zone/aW1nLzgzODc0NTYucG5n/315x250%23c/wEPhAt.png",
								"url": "https://holyguy6455.itch.io/mumei-no-toshi",
								"author": "https://holyguy6455.itch.io",
								"genre": "Simulation",
								"caption": "N/A",
							},
							{
								"id": "1072731",
								"title": "DD shooter-Enhanced Edition [Hololive Fan Game]",
								"thumbnail": "https://img.itch.zone/aW1nLzYxNDkzODIucG5n/315x250%23c/11wWdR.png",
								"url": "https://cky2433.itch.io/dd-shooter-enhanced-edition",
								"author": "https://cky2433.itch.io",
								"genre": "Action",
								"caption": "ééæèµ·ä¾ï¼ç¶åå¥½DDãDonate all Vtubers, be a good DD.",
							},
							{
								"id": "1415250",
								"title": "Hololive RPG",
								"thumbnail": "https://img.itch.zone/aW1nLzgyNDQyMjIuanBn/315x250%23c/uk1nF5.jpg",
								"url": "https://romariomartinus.itch.io/hololive-rpg",
								"author": "https://romariomartinus.itch.io",
								"genre": "Role Playing",
								"caption": "N/A",
							},
							{
								"id": "1185267",
								"title": "Holotalk Speed Round (Hololive fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzY5MDkzOTAucG5n/315x250%23c/tTDeoo.png",
								"url": "https://cobra3279.itch.io/holotalk",
								"author": "https://cobra3279.itch.io",
								"genre": "Interactive Fiction",
								"caption": "N/A",
							},
							{
								"id": "996116",
								"title": "Love Death (Hololive fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzU2NjgyNzkuZ2lm/315x250%23cm/TvVRn9.gif",
								"url": "https://sukaichae.itch.io/love-death",
								"author": "https://sukaichae.itch.io",
								"genre": "Platformer",
								"caption": "Kill yourself for love ~â¥",
							},
							{
								"id": "1459315",
								"title": "Amelia Across Worlds (A Hololive Fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzg1MTk0NDEucG5n/315x250%23c/K1O9vu.png",
								"url": "https://pixelnayt.itch.io/amelia-across-worlds",
								"author": "https://pixelnayt.itch.io",
								"genre": "Survival",
								"caption": "Smol Ame gets chased by Mumei through different levels!",
							},
							{
								"id": "892631",
								"title": "Hololive Horror",
								"thumbnail": "https://img.itch.zone/aW1nLzUxNzU0MzgucG5n/315x250%23c/G3Kw3P.png",
								"url": "https://spartanfandmd.itch.io/hololivehorror",
								"author": "https://spartanfandmd.itch.io",
								"genre": "N/A",
								"caption": "Nothing beats a ground pound!",
							},
							{
								"id": "1569113",
								"title": "Mumei's Birthday Adventure! [Hololive]",
								"thumbnail": "https://img.itch.zone/aW1nLzk3MjE3OTIuanBn/315x250%23c/S9T6q0.jpg",
								"url": "https://vanillapuddingproductions.itch.io/mumeis-birthday-adventure",
								"author": "https://vanillapuddingproductions.itch.io",
								"genre": "Platformer",
								"caption": "A classic platformer made for the occasion of HoloEN's Nanashi Mumei's birthday.",
							},
							{
								"id": "1198143",
								"title": "Hololive Matsuri Widget",
								"thumbnail": "https://img.itch.zone/aW1nLzY5ODk4MTkucG5n/315x250%23c/rfpGJZ.png",
								"url": "https://frydyryck-nietsche.itch.io/matsuri-hololive-widget",
								"author": "https://frydyryck-nietsche.itch.io",
								"genre": "N/A",
								"caption": "Just a Matsuri widget that I made.",
							},
							{
								"id": "1355364",
								"title": "Hololive Figthers - fangame",
								"thumbnail": "https://img.itch.zone/aW1nLzc4ODk3NzAucG5n/315x250%23c/rAREX5.png",
								"url": "https://yinsan.itch.io/holofigth-fan-game",
								"author": "https://yinsan.itch.io",
								"genre": "N/A",
								"caption": "Videojuego de pelea aquÃ­ vamos!! // Fighting game here we come!!",
							},
							{
								"id": "1425607",
								"title": "Hololive Ultimate: Apocrypha",
								"thumbnail": "https://img.itch.zone/aW1nLzgzMzMzNDIucG5n/315x250%23c/kMiVpE.png",
								"url": "https://otomaji.itch.io/hololive-ultimate",
								"author": "https://otomaji.itch.io",
								"genre": "Role Playing",
								"caption": "Custom Game Engine* - Brilliant Idea, Terrible Execution",
							},
							{
								"id": "1191653",
								"title": "Hololive Ayame Soundboard",
								"thumbnail": "https://img.itch.zone/aW1nLzY5NTAzMTYucG5n/315x250%23c/dqx%2FSv.png",
								"url": "https://frydyryck-nietsche.itch.io/hololive-ayame-soundboard",
								"author": "https://frydyryck-nietsche.itch.io",
								"genre": "N/A",
								"caption": "N/A",
							},
							{
								"id": "1603715",
								"title": "Hololive Rhythm Game",
								"thumbnail": "https://img.itch.zone/aW1nLzkzODI2MjQuanBn/315x250%23c/n6j4Di.jpg",
								"url": "https://henrysalazar.itch.io/hololive-rhythm-game",
								"author": "https://henrysalazar.itch.io",
								"genre": "N/A",
								"caption": "N/A",
							},
							{
								"id": "1716254",
								"title": "HoloMan : a Mega Man style hololive fan game (Windows,Android,WebGL))",
								"thumbnail": "https://img.itch.zone/aW1nLzEwMTA5NzgxLnBuZw==/315x250%23c/GcFE%2Fi.png",
								"url": "https://yaoyuanchang.itch.io/holoman-a-mega-man-style-hololive-fan-game-prototype",
								"author": "https://yaoyuanchang.itch.io",
								"genre": "Platformer",
								"caption": "HoloMan",
							},
							{
								"id": "1555401",
								"title": "Hololive Scores [Windows]",
								"thumbnail": "https://img.itch.zone/aW1nLzkwNzUwODQucG5n/315x250%23c/hYB47F.png",
								"url": "https://weloyus.itch.io/holoscores",
								"author": "https://weloyus.itch.io",
								"genre": "Action",
								"caption": "Control your talent to take the champion!",
							},
							{
								"id": "1698475",
								"title": "Reached Over It Gura Test Level Hololive",
								"thumbnail": "https://img.itch.zone/aW1nLzEwMDA2MzE2LnBuZw==/315x250%23c/AyViJk.png",
								"url": "https://mrscottypieey.itch.io/reached-over-it-gura-test-level",
								"author": "https://mrscottypieey.itch.io",
								"genre": "N/A",
								"caption": "N/A",
							},
							{
								"id": "706953",
								"title": "Holovaders (Hololive fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzM5MjU1NjcucG5n/315x250%23c/OumriR.png",
								"url": "https://link1v4n.itch.io/holovaders",
								"author": "https://link1v4n.itch.io",
								"genre": "Shooter",
								"caption": "Takoyaki",
							},
							{
								"id": "1155302",
								"title": "ãã­èª­ã¿ (Hololive fangame)",
								"thumbnail": "https://img.itch.zone/aW1nLzY3MTQ1MTIuanBn/315x250%23c/2z%2Bagr.jpg",
								"url": "https://itzeusmti.itch.io/holoyomi",
								"author": "https://itzeusmti.itch.io",
								"genre": "N/A",
								"caption": "ããªã³è¹é·ã®2å¨å¹´è¨å¿µäºæ¬¡åµä½ã²ã¼ã ",
							},
							{
								"id": "1178368",
								"title": "Hololive Cover Quiz",
								"thumbnail": "https://img.itch.zone/aW1nLzY4NjE5MzYucG5n/315x250%23c/Qce5X%2F.png",
								"url": "https://drweam.itch.io/hololivequiz",
								"author": "https://drweam.itch.io",
								"genre": "N/A",
								"caption": "Guess the singer of the cover!",
							},
							{
								"id": "685041",
								"title": "Hololive Isekai",
								"thumbnail": "https://img.itch.zone/aW1nLzQwNjkzNjkucG5n/315x250%23c/OaDq1f.png",
								"url": "https://drweam.itch.io/hololive-isekai",
								"author": "https://drweam.itch.io",
								"genre": "Role Playing",
								"caption": "Hololivers has been transported to another world!",
							},
							{
								"id": "925627",
								"title": "Polugram Circus",
								"thumbnail": "https://img.itch.zone/aW1nLzUyMzc0ODYucG5n/315x250%23c/apvqoJ.png",
								"url": "https://mevedev.itch.io/polugram-circus",
								"author": "https://mevedev.itch.io",
								"genre": "Platformer",
								"caption": "a hololive fangame -- partial remake of Circus Charlie for the Hololive community",
							},
							{
								"id": "837631",
								"title": "HoloLife",
								"thumbnail": "https://img.itch.zone/aW1nLzY0MDI1MjkucG5n/315x250%23c/sarJOc.png",
								"url": "https://studiosmyles.itch.io/hololife",
								"author": "https://studiosmyles.itch.io",
								"genre": "Visual Novel",
								"caption": "A Hololive fan-made visual novel!",
							},
							{
								"id": "1006795",
								"title": "HololiveEN Portraits",
								"thumbnail": "https://img.itch.zone/aW1nLzU3NDA5MzEucG5n/315x250%23c/Zmu8kf.png",
								"url": "https://chaoticlindo.itch.io/hololiveen-portraits",
								"author": "https://chaoticlindo.itch.io",
								"genre": "N/A",
								"caption": "HololiveE girls",
							},
							{
								"id": "90193",
								"title": "Hololens - The Hidden Facility",
								"thumbnail": "https://img.itch.zone/aW1hZ2UvOTAxOTMvNDIzODI4LmpwZw==/315x250%23c/F%2BSygV.jpg",
								"url": "https://cypherjw.itch.io/hololens-the-hidden-facility",
								"author": "https://cypherjw.itch.io",
								"genre": "Shooter",
								"caption": "Use the hololens to save a hidden facility from a zombie infection",
							},
							{
								"id": "180241",
								"title": "HoloBert (Hololens only)",
								"thumbnail": "https://img.itch.zone/aW1hZ2UvMTgwMjQxLzg0MzkwMi5wbmc=/315x250%23c/YpqmHn.png",
								"url": "https://drgames.itch.io/holobert",
								"author": "https://drgames.itch.io",
								"genre": "Platformer",
								"caption": "A HoloLens game that pays homage to Qbert",
							},
							{
								"id": "506289",
								"title": "GARIE system for HoloLense Prototype",
								"thumbnail": "https://img.itch.zone/aW1nLzI2MjQ2MzcuanBn/315x250%23c/mUmcEp.jpg",
								"url": "https://lukeexe.itch.io/garie",
								"author": "https://lukeexe.itch.io",
								"genre": "Simulation",
								"caption": "Shows some of the features of the proposed system for a hololense application to augment the UoN art gallery experience.",
							},
							{
								"id": "1514441",
								"title": "FLARE NUINUI QUEST",
								"thumbnail": "https://img.itch.zone/aW1nLzkyMjExMjYucG5n/315x250%23c/tJx%2FG1.png",
								"url": "https://sulpx.itch.io/nuinui-quest",
								"author": "https://sulpx.itch.io",
								"genre": "Platformer",
								"caption": "Mega Man style platformer ft. Shiranui Flare and various other Hololive characters",
							},
							{
								"id": "1576684",
								"title": "HoloCure",
								"thumbnail": "https://img.itch.zone/aW1nLzkyODQ0MDYucG5n/315x250%23c/GYujop.png",
								"url": "https://kay-yu.itch.io/holocure",
								"author": "https://kay-yu.itch.io",
								"genre": "Action",
								"caption": "A 'survivors' like, free unofficial Hololive fan game!",
							},
							{
								"id": "926623",
								"title": "Holo EN Rhythm Game",
								"thumbnail": "https://img.itch.zone/aW1nLzUyNTA0NDMucG5n/315x250%23c/hnBnBu.png",
								"url": "https://nullrefrepro.itch.io/hinotori-rhythm",
								"author": "https://nullrefrepro.itch.io",
								"genre": "Rhythm",
								"caption": "A small 8-bit Hololive rhythm game",
							},
							{
								"id": "1756948",
								"title": "HOLOBOOM",
								"thumbnail": "https://img.itch.zone/aW1nLzEwMzM0MTYzLnBuZw==/315x250%23c/hAYo8R.png",
								"url": "https://sulpx.itch.io/holoboom",
								"author": "https://sulpx.itch.io",
								"genre": "Action",
								"caption": "Hot potato but Hololive",
							},
							{
								"id": "1362314",
								"title": "Holotyping - Kanataso edition",
								"thumbnail": "https://img.itch.zone/aW1nLzg5NzY3NTIucG5n/315x250%23c/dbaWs7.png",
								"url": "https://mesiro101.itch.io/holotyping",
								"author": "https://mesiro101.itch.io",
								"genre": "N/A",
								"caption": "A Hololive fan-made typing game / ãã­ã©ã¤ãã®ã¿ã¤ãã³ã°ã²ã¼ã ",
							},
							{
								"id": "926661",
								"title": "ARENA OF THE MYTHS",
								"thumbnail": "https://img.itch.zone/aW1nLzUyNDEzODMucG5n/315x250%23c/wa0%2Fgq.png",
								"url": "https://onegai-project.itch.io/arena-of-the-myths",
								"author": "https://onegai-project.itch.io",
								"genre": "Action",
								"caption": "A fangame for Hololive project",
							},
							{
								"id": "983985",
								"title": "Dream Labyrinth (Version1.0.5)",
								"thumbnail": "https://img.itch.zone/aW1nLzc5MzY0MjkuanBn/315x250%23c/jVaivl.jpg",
								"url": "https://okamiakarutsuki.itch.io/dream-labirynth",
								"author": "https://okamiakarutsuki.itch.io",
								"genre": "Role Playing",
								"caption": "Hololive RPG Fan Game",
							},
							{
								"id": "872394",
								"title": "Gura Tambourine",
								"thumbnail": "https://img.itch.zone/aW1nLzQ5MDUyMDcucG5n/315x250%23c/RjgY76.png",
								"url": "https://nullrefrepro.itch.io/gura-tambourine",
								"author": "https://nullrefrepro.itch.io",
								"genre": "Rhythm",
								"caption": "Gawr Gura / Hololive rhythm fangame",
							},
							{
								"id": "1730350",
								"title": "holoVersus (Test Build)",
								"thumbnail": "https://img.itch.zone/aW1nLzEwMTg4NDU3LnBuZw==/315x250%23c/JPICiP.png",
								"url": "https://zortoise.itch.io/holoversus",
								"author": "https://zortoise.itch.io",
								"genre": "Fighting",
								"caption": "Unofficial Hololive fangame, Platform Fighter prototype",
							},
							{
								"id": "1262671",
								"title": "The Holoween collection",
								"thumbnail": "https://img.itch.zone/aW1nLzc2NzA5MzQucG5n/315x250%23c/cPMl%2F1.png",
								"url": "https://callmemonamiral.itch.io/holoween-collection",
								"author": "https://callmemonamiral.itch.io",
								"genre": "Action",
								"caption": "3 Hololive fangames in one collection",
							},
							{
								"id": "1301619",
								"title": "Whack-a-Miko ã¿ãã¡å©ã",
								"thumbnail": "https://img.itch.zone/aW1nLzc1NzA5ODkucG5n/315x250%23c/WMtmsd.png",
								"url": "https://aoisora-3d.itch.io/whack-a-miko",
								"author": "https://aoisora-3d.itch.io",
								"genre": "Rhythm",
								"caption": "A hololive fan game inspired by Sakura Miko's stream.",
							},
							{
								"id": "1752135",
								"title": "HoloBoss",
								"thumbnail": "https://img.itch.zone/aW1nLzEwMzA2OTE3LnBuZw==/315x250%23c/cZMnob.png",
								"url": "https://hsm-pixelart.itch.io/holoboss",
								"author": "https://hsm-pixelart.itch.io",
								"genre": "Adventure",
								"caption": "Hololive Boss",
							},
							{
								"id": "1188327",
								"title": "GachaLive",
								"thumbnail": "https://img.itch.zone/aW1nLzgwNDkwNjgucG5n/315x250%23c/izspdB.png",
								"url": "https://resisty.itch.io/gachalive",
								"author": "https://resisty.itch.io",
								"genre": "Simulation",
								"caption": "A free Hololive gacha simulator",
							},
							{
								"id": "1427334",
								"title": "Mumei's Memory Juggling",
								"thumbnail": "https://img.itch.zone/aW1nLzgzMTgwNjIucG5n/315x250%23c/GBqoyS.png",
								"url": "https://david-wu-softdev.itch.io/mumeis-memory-juggling",
								"author": "https://david-wu-softdev.itch.io",
								"genre": "Card Game",
								"caption": "Match-2 Hololive game with a twist",
							},
							{
								"id": "1035090",
								"title": "Amelia Watson Case File no.420",
								"thumbnail": "https://img.itch.zone/aW1nLzkyMjAxMzcucG5n/315x250%23c/maQ0VN.png",
								"url": "https://planetdropper.itch.io/ame420",
								"author": "https://planetdropper.itch.io",
								"genre": "Visual Novel",
								"caption": "Finding the answer is about asking the right question.  (hololive Myth fan visual novel)",
							},
							{
								"id": "1424165",
								"title": "Holo Pets",
								"thumbnail": "https://img.itch.zone/aW1nLzg1OTU0NjYucG5n/315x250%23c/aPsmYA.png",
								"url": "https://aakaa.itch.io/holo-pets",
								"author": "https://aakaa.itch.io",
								"genre": "N/A",
								"caption": "Hololive Desktop Pets",
							},
							{
								"id": "969007",
								"title": "immortal: mors tud, vita mea",
								"thumbnail": "https://img.itch.zone/aW1nLzU1MDA1NzMucG5n/315x250%23c/WAqIta.png",
								"url": "https://idaate.itch.io/immortal",
								"author": "https://idaate.itch.io",
								"genre": "Role Playing",
								"caption": "A hololive fangame where you must seek Calliope's help to return to life.",
							},
							{
								"id": "1549960",
								"title": "Sora Game 2.0",
								"thumbnail": "https://img.itch.zone/aW1nLzEwMjA3MDc1LnBuZw==/315x250%23c/1GOG1p.png",
								"url": "https://bugzyfloaty.itch.io/sora-game",
								"author": "https://bugzyfloaty.itch.io",
								"genre": "Platformer",
								"caption": "A fast paced precision platformer featuring Hololive's original idol!",
							},
							{
								"id": "870942",
								"title": "Yubi Yubi Game!",
								"thumbnail": "https://img.itch.zone/aW1nLzQ4OTU1NDgucG5n/315x250%23c/zp%2BRAe.png",
								"url": "https://planetdropper.itch.io/yubiyubi",
								"author": "https://planetdropper.itch.io",
								"genre": "N/A",
								"caption": "Collect yubi for doggo! Yubi Yubi~! (hololive Inugami Korone fangame)",
							},
							{
								"id": "765009",
								"title": "Tsunomaki Janken! - Boss Battle",
								"thumbnail": "https://img.itch.zone/aW1nLzQyODk2MDMuZ2lm/315x250%23cm/7cKEx2.gif",
								"url": "https://numachitamanegi.itch.io/tsunomaki-janken",
								"author": "https://numachitamanegi.itch.io",
								"genre": "Strategy",
								"caption": "A Hololive Fangame",
							},
							{
								"id": "1728988",
								"title": "HoloDive - Down the Rabbit Hole",
								"thumbnail": "https://img.itch.zone/aW1nLzEwMTkwMjM5LnBuZw==/315x250%23c/q04O0Z.png",
								"url": "https://pompmaker1.itch.io/holodive",
								"author": "https://pompmaker1.itch.io",
								"genre": "Action",
								"caption": "Avoid your real life responsibilities as long as you can in this accurate simulation of a crippling hololive addiction!",
							},
						],
					}
				}
			},
		},
	},
	summary="Itch scraper",
)
async def itch(query: Optional[str] = Query(None)):
	"""
	Game search based Itch.io
	"""
	if not query:
		return JSONResponse(
			status_code=406,
			content=jsonable_encoder(
				{"author": AUTHOR, "status": 406, "message": "Invalid query"}
			),
		)
	if Itch(query):
		results = Itch(query)
		return JSONResponse(
			status_code=200,
			content=jsonable_encoder(
				{"author": AUTHOR, "status": 200, "results": results}
			),
		)
	else:
		return JSONResponse(
			status_code=404,
			content=jsonable_encoder(
				{"author": AUTHOR, "status": 404, "message": "Not found!"}
			),
		)
